# RBF neural net

In [1]:
from math import *
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
# cpg model parameters
MI = 0.02
b1 = 0.01
b2 = 0.01
w11 = 1.4
w12 = 0.18 + MI
w21 = -0.18 - MI
w22 = 1.4
o1 = 0.01
o2 = 0.01
# W = [[w11,w21],[w12,w22]]
# O = [o1, o2]

In [ ]:
# cpg running
cpg_out = []
for i in range(300):
    o1 = tanh(o1*w11 + o2*w12 )
    o2 = tanh(o2*w22 + o1*w21 )
    cpg_out.append([o1, o2])
cpg_out = np.array(cpg_out)
plt.figure(figsize=(4,2))
plt.plot(cpg_out[:,0])
plt.plot(cpg_out[:,1])
# cpg_out

In [ ]:
# SO2 oscillator from paper
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
for i in range(1000):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    cpg_out.append([o1, o2])
cpg_out = np.array(cpg_out)
plt.figure(figsize=(4,2))
plt.plot(cpg_out[:,0])
plt.plot(cpg_out[:,1])
# cpg_out

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def generate_rbf_array(input_range, num_basis, centers, widths, weights):
    """
    Generates an array of Radial Basis Functions (RBFs) over a given input range.

    Args:
        input_range (tuple): Range of the input values (e.g., (0, 1)).
        num_basis (int): Number of basis functions.
        centers (ndarray): Array of centers for the basis functions.
        widths (ndarray): Array of widths for the basis functions.

    Returns:
        ndarray: Array of RBFs evaluated over the input range.
    """
    x = np.linspace(input_range[0], input_range[1], num=100)
    rbf_array = np.zeros((num_basis, len(x)))

    for i in range(num_basis):
        rbf_array[i] = weights[i]*np.exp(-widths[i] * (x - centers[i]) ** 2)

    return rbf_array

# Example usage
input_range = (-1, 1)
num_basis = 10
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
widths = np.ones(num_basis) * 100
weights = np.random.randint(input_range[0], input_range[1]+1, 10,)

rbf_array = generate_rbf_array(input_range, num_basis, centers, widths, weights)

# Plotting the RBFs
plt.figure(figsize=(8, 3))
for i in range(num_basis):
    plt.plot(np.linspace(input_range[0], input_range[1], num=100), rbf_array[i], label=f'RBF {i+1}')
plt.xlabel('Input')
plt.ylabel('RBF Value')
plt.title('Array of Radial Basis Functions')
# plt.legend()
plt.show()

In [ ]:
weights

In [ ]:
# cycle checker
T_step = 0
counter = 0
o1_p = 0
# for i in range(10000):
#     o1 = math.tanh(o1*w11 + o2*w12 )
#     o2 = math.tanh(o2*w22 + o1*w21 )
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
cpg_out = []
# Rbf network
input_range = (-1, 1)
num_basis = 10
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
widths = np.ones(num_basis) * 100
x = np.linspace(input_range[0], input_range[1], num=100)
# weights = np.arange(input_range[0], input_range[1], 0.1)
rbf_array = np.zeros((num_basis, len(x)))
T_step = 201
phase = 0 # phase of oscillator
phase_array = []
for step in range(376):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))

for step in range(600):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    # phase = counter/T_step
    # print(t)
    # phase_array.append(phase)
    # cpg_out.append(o1)
    # counter += 1
    if o1_p < 0 and o1 > 0:
        T_step = counter
        print('T_step', T_step)
        print(T_step)
        print(o1_p, o1)
        print('cpg_out: ', len(cpg_out))
        print('phase_array: ', len(phase_array))
        # print('x: ', x)
        # RBF function
        rbf_array = np.zeros((num_basis, T_step))
        print('rbf_array: ', rbf_array.shape)
        for i in range(num_basis):
            rbf_array[i] = np.exp(-widths[i] * (phase_array - centers[i]) ** 2)
        counter = 0
        # Plotting the RBFs
        # plt.figure(figsize=(8, 3))
        # for i in range(num_basis):
        #     plt.plot(np.linspace(input_range[0], input_range[1], num=len(phase_array)), rbf_array[i], label=f'RBF {i+1}')
        # plt.plot(phase_array, np.sum(rbf_array, axis=0))
        # plt.plot(phase_array, cpg_out)
        # plt.xlabel('Input')
        # plt.ylabel('RBF Value')
        # plt.title('Array of Radial Basis Functions')
        # # plt.legend()
        # plt.show()
        cpg_out = []
        phase_array = []
    o1_p = o1


In [ ]:
# RBF network re-produce paper
T_step = 0
counter = 0
o1_p = 0
# for i in range(10000):
#     o1 = math.tanh(o1*w11 + o2*w12 )
#     o2 = math.tanh(o2*w22 + o1*w21 )
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
cpg_out = []
# Rbf network
input_range = (-1, 1)
num_basis = 20
num_output = 2
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
# widths = np.ones(num_basis) * 100
variance = 1/0.04
x = np.linspace(input_range[0], input_range[1], num=100)
# weights = np.arange(input_range[0], input_range[1], 0.1)
# weights = np.random.randint(input_range[0], input_range[1]+1, num_basis,)
weights = np.random.randn(num_output, num_basis)

# rbf_array = np.zeros((num_basis, len(x)))
rbf_array = []
T_step = 201
phase = 0 # phase of oscillator
phase_array = []
for step in range(376):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    print('o1, o2: ', o1, o2)

for step in range(1000):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    cpg_out = [[o1], [o2]]
    # print('o1', o1)
    rbf_array.append(np.sum(weights*np.exp(-variance*(cpg_out - centers) ** 2), axis=1))
    
    if o1_p < 0 and o1 > 0:
        counter = 0
        plt.plot(rbf_array)
        rbf_array = []
        weights = np.random.randn(num_output, num_basis)
        # print('weights: ', weights)
    o1_p = o1


In [ ]:
from rbf_neural_net import RBFNet

In [ ]:
model = RBFNet(1)

In [ ]:
output = []
for i in range(300):
    output.append(model.forward())
    # print('output: ', output)
plt.plot(output)

### Test RBF GPU version

In [ ]:
POPSIZE = 2
omega = 0.01*np.pi
o1 = torch.Tensor.repeat(torch.Tensor([0.00]), POPSIZE).unsqueeze(1)
o2 = torch.Tensor.repeat(torch.Tensor([0.18]), POPSIZE).unsqueeze(1)
O = torch.Tensor([[0.01, 0.18]]).expand(POPSIZE, 2)
# Rbf network
input_range = (-1, 1)
num_basis = 10
num_output = 1
centers = torch.linspace(input_range[0], input_range[1], num_basis)
variance = 1/0.04
weights = torch.randn(num_basis, POPSIZE, num_output,)
rbf_array = []
W = torch.Tensor([[ cos(omega) ,  -sin(omega)], 
                  [ sin(omega) ,  cos(omega)]])

In [ ]:
output = []
with torch.no_grad():
    for i in range(400):
        # o1 = torch.tanh(1.01*( o1p*cos(omega) + o2p*sin(omega)))
        # o2 = torch.tanh(1.01*(-o1p*sin(omega) + o2p*cos(omega)))
        O = torch.tanh(1.01*torch.matmul(O, W))
        # print('o1', o1)
        # posto1 = torch.sum(weights[0]*np.exp(variance*(o1 - centers)), dim=1)
        # posto2 = torch.sum(weights[1]*np.exp(variance*(o2 - centers)), dim=1)
        post = torch.sum(weights*np.exp(-variance*(O - 
            centers.expand(POPSIZE*2,num_basis).transpose(0,1).
            reshape(num_basis,POPSIZE,2)) ** 2), dim=0)
        
        # cpg_out = torch.stack([posto1,posto2])
        output.append(post.tolist())
        o1p = o1
        o2p = o2
plt.plot(np.array(output)[:,0,0])
plt.plot(np.array(output)[:,0,1])
# plt.plot(output[:,1:2])

In [ ]:
post

In [ ]:
np.exp(-variance*(O - centers.expand(POPSIZE*2,num_basis).transpose(0,1).reshape(num_basis,POPSIZE,2)) ** 2)

In [ ]:
output

In [ ]:
# torch.einsum('bp,bqr->bpqr', v, M) # batch-wise operation v.shape=(b,p) M.shape=(b,q,r)
# torch.einsum('p,qr->pqr', v, M)    # cross-batch operation

torch.einsum('p,qr->pqr', -centers, O)    # cross-batch operation


In [2]:
from rbf_neural_net import RBFNet
model = RBFNet(2, 1)

In [3]:
model.forward()

tensor([[-0.2511, -0.4802],
        [ 0.1014,  0.4107]], device='cuda:0')

In [4]:
model.get_params_a_model()

array([ 1.4102287 ,  0.56547713, -1.5049154 , -0.05568573,  0.03879198,
       -0.30321008, -0.40492538,  0.31059295, -0.31220606,  0.09907182],
      dtype=float32)

In [5]:
model.get_params()

array([ 1.4102287 ,  0.6277361 ,  0.56547713, -1.6088862 , -1.5049154 ,
        0.5314756 , -0.05568573, -0.02828681,  0.03879198, -0.01754425,
       -0.30321008,  0.0839266 , -0.40492538,  0.5860087 ,  0.31059295,
        0.4826061 , -0.31220606,  0.16438088,  0.09907182,  1.1455259 ],
      dtype=float32)

In [6]:
model.weights

tensor([[[ 1.4102],
         [ 0.6277]],

        [[ 0.5655],
         [-1.6089]],

        [[-1.5049],
         [ 0.5315]],

        [[-0.0557],
         [-0.0283]],

        [[ 0.0388],
         [-0.0175]],

        [[-0.3032],
         [ 0.0839]],

        [[-0.4049],
         [ 0.5860]],

        [[ 0.3106],
         [ 0.4826]],

        [[-0.3122],
         [ 0.1644]],

        [[ 0.0991],
         [ 1.1455]]], device='cuda:0')

In [7]:
model.set_params(np.random.randn(2,1,10).flatten())

In [8]:
np.random.randn(2,1,10).flatten()

array([-1.01640666,  0.84860013,  1.79264544,  0.09459468, -0.80453952,
       -0.68723667,  0.04438239,  1.53936716, -1.13220157, -0.67814333,
       -0.02244636, -1.22416589,  2.59157711, -2.3961546 , -1.67875475,
       -0.52285505,  0.45370571, -0.69159209,  0.38836375,  2.1324957 ])

In [9]:
model.get_weights()

[tensor([[1.1993],
         [1.5869]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.6357],
         [-0.5430]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.3161],
         [-0.4185]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.5011],
         [-0.9888]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.2242],
         [-1.0559]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.3508],
         [-0.8669]], device='cuda:0', dtype=torch.float64),
 tensor([[0.5236],
         [0.4405]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.7479],
         [ 0.4421]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.0474],
         [-1.4641]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.8154],
         [-0.4103]], device='cuda:0', dtype=torch.float64)]