# RBF neural net

In [2]:
from math import *
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
# cpg model parameters
MI = 0.02
b1 = 0.01
b2 = 0.01
w11 = 1.4
w12 = 0.18 + MI
w21 = -0.18 - MI
w22 = 1.4
o1 = 0.01
o2 = 0.01
# W = [[w11,w21],[w12,w22]]
# O = [o1, o2]

In [ ]:
# cpg running
cpg_out = []
for i in range(300):
    o1 = tanh(o1*w11 + o2*w12 )
    o2 = tanh(o2*w22 + o1*w21 )
    cpg_out.append([o1, o2])
cpg_out = np.array(cpg_out)
plt.figure(figsize=(4,2))
plt.plot(cpg_out[:,0])
plt.plot(cpg_out[:,1])
# cpg_out

In [ ]:
# SO2 oscillator from paper
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
for i in range(1000):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    cpg_out.append([o1, o2])
cpg_out = np.array(cpg_out)
plt.figure(figsize=(4,2))
plt.plot(cpg_out[:,0])
plt.plot(cpg_out[:,1])
# cpg_out

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def generate_rbf_array(input_range, num_basis, centers, widths, weights):
    """
    Generates an array of Radial Basis Functions (RBFs) over a given input range.

    Args:
        input_range (tuple): Range of the input values (e.g., (0, 1)).
        num_basis (int): Number of basis functions.
        centers (ndarray): Array of centers for the basis functions.
        widths (ndarray): Array of widths for the basis functions.

    Returns:
        ndarray: Array of RBFs evaluated over the input range.
    """
    x = np.linspace(input_range[0], input_range[1], num=100)
    rbf_array = np.zeros((num_basis, len(x)))

    for i in range(num_basis):
        rbf_array[i] = weights[i]*np.exp(-widths[i] * (x - centers[i]) ** 2)

    return rbf_array

# Example usage
input_range = (-1, 1)
num_basis = 10
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
widths = np.ones(num_basis) * 100
weights = np.random.randint(input_range[0], input_range[1]+1, 10,)

rbf_array = generate_rbf_array(input_range, num_basis, centers, widths, weights)

# Plotting the RBFs
plt.figure(figsize=(8, 3))
for i in range(num_basis):
    plt.plot(np.linspace(input_range[0], input_range[1], num=100), rbf_array[i], label=f'RBF {i+1}')
plt.xlabel('Input')
plt.ylabel('RBF Value')
plt.title('Array of Radial Basis Functions')
# plt.legend()
plt.show()

In [ ]:
weights

In [ ]:
# cycle checker
T_step = 0
counter = 0
o1_p = 0
# for i in range(10000):
#     o1 = math.tanh(o1*w11 + o2*w12 )
#     o2 = math.tanh(o2*w22 + o1*w21 )
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
cpg_out = []
# Rbf network
input_range = (-1, 1)
num_basis = 10
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
widths = np.ones(num_basis) * 100
x = np.linspace(input_range[0], input_range[1], num=100)
# weights = np.arange(input_range[0], input_range[1], 0.1)
rbf_array = np.zeros((num_basis, len(x)))
T_step = 201
phase = 0 # phase of oscillator
phase_array = []
for step in range(376):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))

for step in range(600):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    # phase = counter/T_step
    # print(t)
    # phase_array.append(phase)
    # cpg_out.append(o1)
    # counter += 1
    if o1_p < 0 and o1 > 0:
        T_step = counter
        print('T_step', T_step)
        print(T_step)
        print(o1_p, o1)
        print('cpg_out: ', len(cpg_out))
        print('phase_array: ', len(phase_array))
        # print('x: ', x)
        # RBF function
        rbf_array = np.zeros((num_basis, T_step))
        print('rbf_array: ', rbf_array.shape)
        for i in range(num_basis):
            rbf_array[i] = np.exp(-widths[i] * (phase_array - centers[i]) ** 2)
        counter = 0
        # Plotting the RBFs
        # plt.figure(figsize=(8, 3))
        # for i in range(num_basis):
        #     plt.plot(np.linspace(input_range[0], input_range[1], num=len(phase_array)), rbf_array[i], label=f'RBF {i+1}')
        # plt.plot(phase_array, np.sum(rbf_array, axis=0))
        # plt.plot(phase_array, cpg_out)
        # plt.xlabel('Input')
        # plt.ylabel('RBF Value')
        # plt.title('Array of Radial Basis Functions')
        # # plt.legend()
        # plt.show()
        cpg_out = []
        phase_array = []
    o1_p = o1


In [ ]:
# RBF network re-produce paper
T_step = 0
counter = 0
o1_p = 0
# for i in range(10000):
#     o1 = math.tanh(o1*w11 + o2*w12 )
#     o2 = math.tanh(o2*w22 + o1*w21 )
cpg_out = []
omega = 0.01*pi
o1, o2 = 0.01, 0.01
cpg_out = []
# Rbf network
input_range = (-1, 1)
num_basis = 20
num_output = 2
centers = np.linspace(input_range[0], input_range[1], num=num_basis)
# widths = np.ones(num_basis) * 100
variance = 1/0.04
x = np.linspace(input_range[0], input_range[1], num=100)
# weights = np.arange(input_range[0], input_range[1], 0.1)
# weights = np.random.randint(input_range[0], input_range[1]+1, num_basis,)
weights = np.random.randn(num_output, num_basis)

# rbf_array = np.zeros((num_basis, len(x)))
rbf_array = []
T_step = 201
phase = 0 # phase of oscillator
phase_array = []
for step in range(376):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    print('o1, o2: ', o1, o2)

for step in range(1000):
    o1 = tanh(1.01*( o1*cos(omega) + o2*sin(omega)))
    o2 = tanh(1.01*(-o1*sin(omega) + o2*cos(omega)))
    cpg_out = [[o1], [o2]]
    # print('o1', o1)
    rbf_array.append(np.sum(weights*np.exp(-variance*(cpg_out - centers) ** 2), axis=1))
    
    if o1_p < 0 and o1 > 0:
        counter = 0
        plt.plot(rbf_array)
        rbf_array = []
        weights = np.random.randn(num_output, num_basis)
        # print('weights: ', weights)
    o1_p = o1


In [ ]:
from rbf_neural_net import RBFNet

In [ ]:
model = RBFNet(1)

In [ ]:
output = []
for i in range(300):
    output.append(model.forward())
    # print('output: ', output)
plt.plot(output)

### Test RBF GPU version

In [3]:
POPSIZE = 2
omega = 0.01*np.pi
o1 = torch.Tensor.repeat(torch.Tensor([0.00]), POPSIZE).unsqueeze(1)
o2 = torch.Tensor.repeat(torch.Tensor([0.18]), POPSIZE).unsqueeze(1)
O = torch.Tensor([[0.01, 0.18]]).expand(POPSIZE, 2)
# Rbf network
input_range = (-1, 1)
num_basis = 10
num_output = 3
centers = torch.linspace(input_range[0], input_range[1], num_basis)
variance = 1/0.04
weights = torch.randn(num_basis, POPSIZE, num_output,)
rbf_array = []
W = torch.Tensor([[ cos(omega) ,  -sin(omega)], 
                  [ sin(omega) ,  cos(omega)]])

In [4]:
output = []
with torch.no_grad():
    for i in range(400):
        # o1 = torch.tanh(1.01*( o1p*cos(omega) + o2p*sin(omega)))
        # o2 = torch.tanh(1.01*(-o1p*sin(omega) + o2p*cos(omega)))
        O = torch.tanh(1.01*torch.matmul(O, W))
        # print('o1', o1)
        # posto1 = torch.sum(weights[0]*np.exp(variance*(o1 - centers)), dim=1)
        # posto2 = torch.sum(weights[1]*np.exp(variance*(o2 - centers)), dim=1)
        post = weights*torch.exp(-variance*(O - 
            centers.expand(POPSIZE*2,num_basis).transpose(0,1).
            reshape(num_basis,POPSIZE,2)) ** 2)
        
        # cpg_out = torch.stack([posto1,posto2])
        output.append(post.tolist())
        o1p = o1
        o2p = o2
    print(torch.sum(post, dim=[0,2]).unsqueeze(1))
plt.plot(np.array(output)[:,0,0])
plt.plot(np.array(output)[:,0,1])
# plt.plot(output[:,1:2])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [5]:
weights*torch.exp(-variance*(O - 
            centers.expand(POPSIZE*2,num_basis).transpose(0,1).
            reshape(num_basis,POPSIZE,2)) ** 2)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

In [6]:
torch.exp(-variance*(O - 
            centers.expand(POPSIZE*2,num_basis).transpose(0,1).
            reshape(num_basis,POPSIZE,2)) ** 2)

tensor([[[6.2624e-12, 7.8854e-16],
         [6.2624e-12, 7.8854e-16]],

        [[1.4532e-07, 1.1272e-10],
         [1.4532e-07, 1.1272e-10]],

        [[2.8549e-04, 1.3640e-06],
         [2.8549e-04, 1.3640e-06]],

        [[4.7481e-02, 1.3974e-03],
         [4.7481e-02, 1.3974e-03]],

        [[6.6852e-01, 1.2120e-01],
         [6.6852e-01, 1.2120e-01]],

        [[7.9685e-01, 8.8987e-01],
         [7.9685e-01, 8.8987e-01]],

        [[8.0410e-02, 5.5313e-01],
         [8.0410e-02, 5.5313e-01]],

        [[6.8692e-04, 2.9107e-02],
         [6.8692e-04, 2.9107e-02]],

        [[4.9679e-07, 1.2967e-04],
         [4.9679e-07, 1.2967e-04]],

        [[3.0417e-11, 4.8904e-08],
         [3.0417e-11, 4.8904e-08]]])

In [7]:
weights

tensor([[[ 1.3960,  0.8463,  0.5061],
         [ 0.2773,  0.3979, -0.8531]],

        [[-0.0276,  1.5780,  0.2846],
         [-1.6488,  0.4776, -0.2948]],

        [[-0.3185,  1.6473,  0.2779],
         [-1.0182, -0.2150, -0.4937]],

        [[ 2.1363, -0.3781,  1.9848],
         [-1.3986, -0.7353,  3.0488]],

        [[-0.4251,  1.1283, -0.0130],
         [-1.8840,  1.9454,  0.4473]],

        [[ 1.5352, -0.8769,  1.8093],
         [-0.3514, -1.3196, -0.5822]],

        [[ 0.7504,  0.7699, -0.9024],
         [ 0.0642, -0.7769,  0.9157]],

        [[-0.5078, -0.7582, -0.3647],
         [-1.2193,  0.3764, -0.4377]],

        [[ 0.5861, -0.2080, -1.1104],
         [ 0.4127, -1.8124, -0.2593]],

        [[-0.5691,  0.3451,  0.3546],
         [-0.1559,  1.0370, -1.4523]]])

In [33]:
a = weights*np.exp(-variance*(O - 
            centers.expand(POPSIZE*2,num_basis).transpose(0,1).
            reshape(num_basis,POPSIZE,2)) ** 2)
torch.sum(torch.eye)

tensor([[-1.3842e-10, -2.6447e-16],
        [ 1.7015e-10,  3.2509e-16]])

In [37]:
torch.sum(torch.eye(2,2,2), dim=[0])

TypeError: eye() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [56]:
torch.sum(torch.Tensor([[[1,1], 
            [2,2]], 
            [[0,0], 
            [0,0]]]), dim=[2])

tensor([[2., 4.],
        [0., 0.]])

In [ ]:
# torch.einsum('bp,bqr->bpqr', v, M) # batch-wise operation v.shape=(b,p) M.shape=(b,q,r)
# torch.einsum('p,qr->pqr', v, M)    # cross-batch operation

torch.einsum('p,qr->pqr', -centers, O)    # cross-batch operation


In [2]:
from rbf_neural_net import RBFNet
model = RBFNet(2, 1)

tensor([[0.0100, 0.1800]])


In [4]:
model.forward([1])

tensor([-1.1732, -3.1462], device='cuda:0')

In [18]:
model.get_params_a_model()

array([ 0.06230127,  0.25622773, -1.4507684 , -0.776767  ,  1.1257079 ,
        0.26371974,  0.291008  , -1.3694811 ,  1.1670934 ,  0.3386766 ],
      dtype=float32)

In [5]:
model.get_params()

array([ 1.4102287 ,  0.6277361 ,  0.56547713, -1.6088862 , -1.5049154 ,
        0.5314756 , -0.05568573, -0.02828681,  0.03879198, -0.01754425,
       -0.30321008,  0.0839266 , -0.40492538,  0.5860087 ,  0.31059295,
        0.4826061 , -0.31220606,  0.16438088,  0.09907182,  1.1455259 ],
      dtype=float32)

In [6]:
model.weights

tensor([[[ 1.4102],
         [ 0.6277]],

        [[ 0.5655],
         [-1.6089]],

        [[-1.5049],
         [ 0.5315]],

        [[-0.0557],
         [-0.0283]],

        [[ 0.0388],
         [-0.0175]],

        [[-0.3032],
         [ 0.0839]],

        [[-0.4049],
         [ 0.5860]],

        [[ 0.3106],
         [ 0.4826]],

        [[-0.3122],
         [ 0.1644]],

        [[ 0.0991],
         [ 1.1455]]], device='cuda:0')

In [7]:
model.set_params(np.random.randn(2,1,10).flatten())

In [8]:
np.random.randn(2,1,10).flatten()

array([-1.01640666,  0.84860013,  1.79264544,  0.09459468, -0.80453952,
       -0.68723667,  0.04438239,  1.53936716, -1.13220157, -0.67814333,
       -0.02244636, -1.22416589,  2.59157711, -2.3961546 , -1.67875475,
       -0.52285505,  0.45370571, -0.69159209,  0.38836375,  2.1324957 ])

In [9]:
model.get_weights()

[tensor([[1.1993],
         [1.5869]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.6357],
         [-0.5430]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.3161],
         [-0.4185]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.5011],
         [-0.9888]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.2242],
         [-1.0559]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.3508],
         [-0.8669]], device='cuda:0', dtype=torch.float64),
 tensor([[0.5236],
         [0.4405]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.7479],
         [ 0.4421]], device='cuda:0', dtype=torch.float64),
 tensor([[ 1.0474],
         [-1.4641]], device='cuda:0', dtype=torch.float64),
 tensor([[-0.8154],
         [-0.4103]], device='cuda:0', dtype=torch.float64)]